#!/bin/bash
#
# Copyright (c) 2012, Luke Southam <luke@devthe.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# - Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
#
# - Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in
#   the documentation and/or other materials provided with the
#   distribution.
#
# - Neither the name of the DEVTHE.COM LIMITED nor the names of its
#   contributors may be used to endorse or promote products derived
#   from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
# THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $DIR/project_vars.sh

cd $DIR/../app

lake.py -fq
echo compiled app/less/*.less to app/static/css/*.css
coffee -c -o coffee/*.coffee static/js
echo compiled coffee/*.coffee to static/js/*.js
cd ..

pid=`lsof -i tcp:8080 | tail -n +2 | awk '{print $2}'`

if [ ! -z "$pid" ]
then
	kill $pid
fi

echo starting server
dev_appserver.py app &
SERVER_PID=$!

PWD=`pwd`

SERVER=" --app=http://localhost:8080/"
cmd="chromium-browser --temp-profile --app=http://localhost:8080/"

if [ $# == 0 ]
then
	cmd+=$SERVER
fi

for arg in $@
do
	path=`realpath $arg`
	cmd+=$SERVER
	cmd+=${path:${#PWD}}
	cmd+="/"
done

sleep 10

echo starting chrome
$cmd

kill $SERVER_PID
